# Generated by Django 6.1.1 on 2026-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_property_description_en_property_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_ky',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2),
        ),
    ]
