# Generated by Django 6.1.1 on 2026-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_remove_property_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
